<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\AddProductEndDate;

/**
 * Builder for model AddProductEndDate
 *
 * @see AddProductEndDate
 */
class AddProductEndDateBuilder
{
    /**
     * @var AddProductEndDate
     */
    private $instance;

    private function __construct(AddProductEndDate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Add Product End Date Builder object.
     */
    public static function init(): self
    {
        return new self(new AddProductEndDate());
    }

    /**
     * Sets end Date Condition field.
     *
     * @param string|null $value
     */
    public function endDateCondition(?string $value): self
    {
        $this->instance->setEndDateCondition($value);
        return $this;
    }

    /**
     * Sets specific End Date field.
     *
     * @param string|null $value
     */
    public function specificEndDate(?string $value): self
    {
        $this->instance->setSpecificEndDate($value);
        return $this;
    }

    /**
     * Sets up To Periods field.
     *
     * @param float|null $value
     */
    public function upToPeriods(?float $value): self
    {
        $this->instance->setUpToPeriods($value);
        return $this;
    }

    /**
     * Sets up To Periods Type field.
     *
     * @param string|null $value
     */
    public function upToPeriodsType(?string $value): self
    {
        $this->instance->setUpToPeriodsType($value);
        return $this;
    }

    /**
     * Initializes a new Add Product End Date object.
     */
    public function build(): AddProductEndDate
    {
        return CoreHelper::clone($this->instance);
    }
}
