<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\AuthError;

/**
 * Builder for model AuthError
 *
 * @see AuthError
 */
class AuthErrorBuilder
{
    /**
     * @var AuthError
     */
    private $instance;

    private function __construct(AuthError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Auth Error Builder object.
     */
    public static function init(): self
    {
        return new self(new AuthError());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Auth Error object.
     */
    public function build(): AuthError
    {
        return CoreHelper::clone($this->instance);
    }
}
