<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\BillToContactPostOrder;

/**
 * Builder for model BillToContactPostOrder
 *
 * @see BillToContactPostOrder
 */
class BillToContactPostOrderBuilder
{
    /**
     * @var BillToContactPostOrder
     */
    private $instance;

    private function __construct(BillToContactPostOrder $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Bill To Contact Post Order Builder object.
     */
    public static function init(): self
    {
        return new self(new BillToContactPostOrder());
    }

    /**
     * Sets address 1 field.
     *
     * @param string|null $value
     */
    public function address1(?string $value): self
    {
        $this->instance->setAddress1($value);
        return $this;
    }

    /**
     * Sets address 2 field.
     *
     * @param string|null $value
     */
    public function address2(?string $value): self
    {
        $this->instance->setAddress2($value);
        return $this;
    }

    /**
     * Sets city field.
     *
     * @param string|null $value
     */
    public function city(?string $value): self
    {
        $this->instance->setCity($value);
        return $this;
    }

    /**
     * Sets country field.
     *
     * @param string|null $value
     */
    public function country(?string $value): self
    {
        $this->instance->setCountry($value);
        return $this;
    }

    /**
     * Sets county field.
     *
     * @param string|null $value
     */
    public function county(?string $value): self
    {
        $this->instance->setCounty($value);
        return $this;
    }

    /**
     * Sets first Name field.
     *
     * @param string|null $value
     */
    public function firstName(?string $value): self
    {
        $this->instance->setFirstName($value);
        return $this;
    }

    /**
     * Sets last Name field.
     *
     * @param string|null $value
     */
    public function lastName(?string $value): self
    {
        $this->instance->setLastName($value);
        return $this;
    }

    /**
     * Sets mobile Phone field.
     *
     * @param string|null $value
     */
    public function mobilePhone(?string $value): self
    {
        $this->instance->setMobilePhone($value);
        return $this;
    }

    /**
     * Sets personal Email field.
     *
     * @param string|null $value
     */
    public function personalEmail(?string $value): self
    {
        $this->instance->setPersonalEmail($value);
        return $this;
    }

    /**
     * Sets postal Code field.
     *
     * @param string|null $value
     */
    public function postalCode(?string $value): self
    {
        $this->instance->setPostalCode($value);
        return $this;
    }

    /**
     * Sets state field.
     *
     * @param string|null $value
     */
    public function state(?string $value): self
    {
        $this->instance->setState($value);
        return $this;
    }

    /**
     * Sets work Email field.
     *
     * @param string|null $value
     */
    public function workEmail(?string $value): self
    {
        $this->instance->setWorkEmail($value);
        return $this;
    }

    /**
     * Sets work Phone field.
     *
     * @param string|null $value
     */
    public function workPhone(?string $value): self
    {
        $this->instance->setWorkPhone($value);
        return $this;
    }

    /**
     * Initializes a new Bill To Contact Post Order object.
     */
    public function build(): BillToContactPostOrder
    {
        return CoreHelper::clone($this->instance);
    }
}
