<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\BillingOptions;

/**
 * Builder for model BillingOptions
 *
 * @see BillingOptions
 */
class BillingOptionsBuilder
{
    /**
     * @var BillingOptions
     */
    private $instance;

    private function __construct(BillingOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Billing Options Builder object.
     */
    public static function init(): self
    {
        return new self(new BillingOptions());
    }

    /**
     * Sets document Date field.
     *
     * @param \DateTime|null $value
     */
    public function documentDate(?\DateTime $value): self
    {
        $this->instance->setDocumentDate($value);
        return $this;
    }

    /**
     * Sets target Date field.
     *
     * @param \DateTime|null $value
     */
    public function targetDate(?\DateTime $value): self
    {
        $this->instance->setTargetDate($value);
        return $this;
    }

    /**
     * Initializes a new Billing Options object.
     */
    public function build(): BillingOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
