<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\CancelResType;

/**
 * Builder for model CancelResType
 *
 * @see CancelResType
 */
class CancelResTypeBuilder
{
    /**
     * @var CancelResType
     */
    private $instance;

    private function __construct(CancelResType $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Cancel Res Type Builder object.
     *
     * @param string $message
     */
    public static function init(string $message): self
    {
        return new self(new CancelResType($message));
    }

    /**
     * Initializes a new Cancel Res Type object.
     */
    public function build(): CancelResType
    {
        return CoreHelper::clone($this->instance);
    }
}
