<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\CreateSubscription;
use PplusSubscriptionPapiLib\Models\SubscribeToRatePlan;
use PplusSubscriptionPapiLib\Models\Terms;

/**
 * Builder for model CreateSubscription
 *
 * @see CreateSubscription
 */
class CreateSubscriptionBuilder
{
    /**
     * @var CreateSubscription
     */
    private $instance;

    private function __construct(CreateSubscription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Subscription Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateSubscription());
    }

    /**
     * Sets terms field.
     *
     * @param Terms|null $value
     */
    public function terms(?Terms $value): self
    {
        $this->instance->setTerms($value);
        return $this;
    }

    /**
     * Sets subscribe To Rate Plans field.
     *
     * @param SubscribeToRatePlan[]|null $value
     */
    public function subscribeToRatePlans(?array $value): self
    {
        $this->instance->setSubscribeToRatePlans($value);
        return $this;
    }

    /**
     * Initializes a new Create Subscription object.
     */
    public function build(): CreateSubscription
    {
        return CoreHelper::clone($this->instance);
    }
}
