<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\CreateOrderOrderAction;
use PearsonSubscriptionsAPILib\Models\CreateSubscription;
use PearsonSubscriptionsAPILib\Models\TriggerDate;

/**
 * Builder for model CreateOrderOrderAction
 *
 * @see CreateOrderOrderAction
 */
class CreateOrderOrderActionBuilder
{
    /**
     * @var CreateOrderOrderAction
     */
    private $instance;

    private function __construct(CreateOrderOrderAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Create Order Order Action Builder object.
     */
    public static function init(): self
    {
        return new self(new CreateOrderOrderAction());
    }

    /**
     * Sets type field.
     *
     * @param string|null $value
     */
    public function type(?string $value): self
    {
        $this->instance->setType($value);
        return $this;
    }

    /**
     * Sets trigger Dates field.
     *
     * @param TriggerDate[]|null $value
     */
    public function triggerDates(?array $value): self
    {
        $this->instance->setTriggerDates($value);
        return $this;
    }

    /**
     * Sets create Subscription field.
     *
     * @param CreateSubscription|null $value
     */
    public function createSubscription(?CreateSubscription $value): self
    {
        $this->instance->setCreateSubscription($value);
        return $this;
    }

    /**
     * Initializes a new Create Order Order Action object.
     */
    public function build(): CreateOrderOrderAction
    {
        return CoreHelper::clone($this->instance);
    }
}
