<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\CustomerFacingCustomFields;

/**
 * Builder for model CustomerFacingCustomFields
 *
 * @see CustomerFacingCustomFields
 */
class CustomerFacingCustomFieldsBuilder
{
    /**
     * @var CustomerFacingCustomFields
     */
    private $instance;

    private function __construct(CustomerFacingCustomFields $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Customer Facing Custom Fields Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomerFacingCustomFields());
    }

    /**
     * Sets customer Facing c field.
     *
     * @param string|null $value
     */
    public function customerFacingC(?string $value): self
    {
        $this->instance->setCustomerFacingC($value);
        return $this;
    }

    /**
     * Initializes a new Customer Facing Custom Fields object.
     */
    public function build(): CustomerFacingCustomFields
    {
        return CoreHelper::clone($this->instance);
    }
}
