<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\CustomField;

/**
 * Builder for model CustomField
 *
 * @see CustomField
 */
class CustomFieldBuilder
{
    /**
     * @var CustomField
     */
    private $instance;

    private function __construct(CustomField $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Custom Field Builder object.
     */
    public static function init(): self
    {
        return new self(new CustomField());
    }

    /**
     * Sets name field.
     *
     * @param string|null $value
     */
    public function name(?string $value): self
    {
        $this->instance->setName($value);
        return $this;
    }

    /**
     * Sets value field.
     *
     * @param string|null $value
     */
    public function value(?string $value): self
    {
        $this->instance->setValue($value);
        return $this;
    }

    /**
     * Initializes a new Custom Field object.
     */
    public function build(): CustomField
    {
        return CoreHelper::clone($this->instance);
    }
}
