<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\Discount;

/**
 * Builder for model Discount
 *
 * @see Discount
 */
class DiscountBuilder
{
    /**
     * @var Discount
     */
    private $instance;

    private function __construct(Discount $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Discount Builder object.
     */
    public static function init(): self
    {
        return new self(new Discount());
    }

    /**
     * Sets discount Amount field.
     *
     * @param float|null $value
     */
    public function discountAmount(?float $value): self
    {
        $this->instance->setDiscountAmount($value);
        return $this;
    }

    /**
     * Sets discount Percentage field.
     *
     * @param float|null $value
     */
    public function discountPercentage(?float $value): self
    {
        $this->instance->setDiscountPercentage($value);
        return $this;
    }

    /**
     * Initializes a new Discount object.
     */
    public function build(): Discount
    {
        return CoreHelper::clone($this->instance);
    }
}
