<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\InitialTerm;

/**
 * Builder for model InitialTerm
 *
 * @see InitialTerm
 */
class InitialTermBuilder
{
    /**
     * @var InitialTerm
     */
    private $instance;

    private function __construct(InitialTerm $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Initial Term Builder object.
     */
    public static function init(): self
    {
        return new self(new InitialTerm());
    }

    /**
     * Sets start Date field.
     *
     * @param string|null $value
     */
    public function startDate(?string $value): self
    {
        $this->instance->setStartDate($value);
        return $this;
    }

    /**
     * Sets end Date field.
     *
     * @param string|null $value
     */
    public function endDate(?string $value): self
    {
        $this->instance->setEndDate($value);
        return $this;
    }

    /**
     * Sets period field.
     *
     * @param int|null $value
     */
    public function period(?int $value): self
    {
        $this->instance->setPeriod($value);
        return $this;
    }

    /**
     * Sets period Type field.
     *
     * @param string|null $value
     */
    public function periodType(?string $value): self
    {
        $this->instance->setPeriodType($value);
        return $this;
    }

    /**
     * Sets term Type field.
     *
     * @param string|null $value
     */
    public function termType(?string $value): self
    {
        $this->instance->setTermType($value);
        return $this;
    }

    /**
     * Initializes a new Initial Term object.
     */
    public function build(): InitialTerm
    {
        return CoreHelper::clone($this->instance);
    }
}
