<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\InvalidReqTypeError;

/**
 * Builder for model InvalidReqTypeError
 *
 * @see InvalidReqTypeError
 */
class InvalidReqTypeErrorBuilder
{
    /**
     * @var InvalidReqTypeError
     */
    private $instance;

    private function __construct(InvalidReqTypeError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Invalid Req Type Error Builder object.
     */
    public static function init(): self
    {
        return new self(new InvalidReqTypeError());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Invalid Req Type Error object.
     */
    public function build(): InvalidReqTypeError
    {
        return CoreHelper::clone($this->instance);
    }
}
