<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\OrderError;

/**
 * Builder for model OrderError
 *
 * @see OrderError
 */
class OrderErrorBuilder
{
    /**
     * @var OrderError
     */
    private $instance;

    private function __construct(OrderError $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Error Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderError());
    }

    /**
     * Sets code field.
     *
     * @param string|null $value
     */
    public function code(?string $value): self
    {
        $this->instance->setCode($value);
        return $this;
    }

    /**
     * Sets message field.
     *
     * @param string|null $value
     */
    public function message(?string $value): self
    {
        $this->instance->setMessage($value);
        return $this;
    }

    /**
     * Initializes a new Order Error object.
     */
    public function build(): OrderError
    {
        return CoreHelper::clone($this->instance);
    }
}
