<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\BillingOptions;
use PearsonSubscriptionsAPILib\Models\OrderRequestProcessingOptions;

/**
 * Builder for model OrderRequestProcessingOptions
 *
 * @see OrderRequestProcessingOptions
 */
class OrderRequestProcessingOptionsBuilder
{
    /**
     * @var OrderRequestProcessingOptions
     */
    private $instance;

    private function __construct(OrderRequestProcessingOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Request Processing Options Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderRequestProcessingOptions());
    }

    /**
     * Sets run Billing field.
     *
     * @param bool|null $value
     */
    public function runBilling(?bool $value): self
    {
        $this->instance->setRunBilling($value);
        return $this;
    }

    /**
     * Sets billing Options field.
     *
     * @param BillingOptions|null $value
     */
    public function billingOptions(?BillingOptions $value): self
    {
        $this->instance->setBillingOptions($value);
        return $this;
    }

    /**
     * Sets collect Payment field.
     *
     * @param bool|null $value
     */
    public function collectPayment(?bool $value): self
    {
        $this->instance->setCollectPayment($value);
        return $this;
    }

    /**
     * Initializes a new Order Request Processing Options object.
     */
    public function build(): OrderRequestProcessingOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
