<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\Account;
use PearsonSubscriptionsAPILib\Models\CustomField;
use PearsonSubscriptionsAPILib\Models\OrderRequestProcessingOptions;
use PearsonSubscriptionsAPILib\Models\OrderRequestType;
use PearsonSubscriptionsAPILib\Models\OrderRequestTypeProduct;
use PearsonSubscriptionsAPILib\Models\OrderRequestTypeSubscription;

/**
 * Builder for model OrderRequestType
 *
 * @see OrderRequestType
 */
class OrderRequestTypeBuilder
{
    /**
     * @var OrderRequestType
     */
    private $instance;

    private function __construct(OrderRequestType $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Request Type Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderRequestType());
    }

    /**
     * Sets order Number field.
     *
     * @param string|null $value
     */
    public function orderNumber(?string $value): self
    {
        $this->instance->setOrderNumber($value);
        return $this;
    }

    /**
     * Sets order Date field.
     *
     * @param \DateTime|null $value
     */
    public function orderDate(?\DateTime $value): self
    {
        $this->instance->setOrderDate($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets subscription Model Name field.
     *
     * @param string|null $value
     */
    public function subscriptionModelName(?string $value): self
    {
        $this->instance->setSubscriptionModelName($value);
        return $this;
    }

    /**
     * Sets store Code field.
     *
     * @param string|null $value
     */
    public function storeCode(?string $value): self
    {
        $this->instance->setStoreCode($value);
        return $this;
    }

    /**
     * Sets swap Title field.
     *
     * @param bool|null $value
     */
    public function swapTitle(?bool $value): self
    {
        $this->instance->setSwapTitle($value);
        return $this;
    }

    /**
     * Sets send Email field.
     *
     * @param bool|null $value
     */
    public function sendEmail(?bool $value): self
    {
        $this->instance->setSendEmail($value);
        return $this;
    }

    /**
     * Sets account field.
     *
     * @param Account|null $value
     */
    public function account(?Account $value): self
    {
        $this->instance->setAccount($value);
        return $this;
    }

    /**
     * Sets order Request Type Subscriptions field.
     *
     * @param OrderRequestTypeSubscription[]|null $value
     */
    public function orderRequestTypeSubscriptions(?array $value): self
    {
        $this->instance->setOrderRequestTypeSubscriptions($value);
        return $this;
    }

    /**
     * Sets order Request Processing Options field.
     *
     * @param OrderRequestProcessingOptions|null $value
     */
    public function orderRequestProcessingOptions(?OrderRequestProcessingOptions $value): self
    {
        $this->instance->setOrderRequestProcessingOptions($value);
        return $this;
    }

    /**
     * Sets order Request Type Products field.
     *
     * @param OrderRequestTypeProduct[]|null $value
     */
    public function orderRequestTypeProducts(?array $value): self
    {
        $this->instance->setOrderRequestTypeProducts($value);
        return $this;
    }

    /**
     * Sets custom Fields field.
     *
     * @param CustomField[]|null $value
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets payment Capture field.
     *
     * @param array|null $value
     */
    public function paymentCapture(?array $value): self
    {
        $this->instance->setPaymentCapture($value);
        return $this;
    }

    /**
     * Initializes a new Order Request Type object.
     */
    public function build(): OrderRequestType
    {
        return CoreHelper::clone($this->instance);
    }
}
