<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\OrderRequestTypeProduct;

/**
 * Builder for model OrderRequestTypeProduct
 *
 * @see OrderRequestTypeProduct
 */
class OrderRequestTypeProductBuilder
{
    /**
     * @var OrderRequestTypeProduct
     */
    private $instance;

    private function __construct(OrderRequestTypeProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Order Request Type Product Builder object.
     */
    public static function init(): self
    {
        return new self(new OrderRequestTypeProduct());
    }

    /**
     * Sets isbn field.
     *
     * @param string|null $value
     */
    public function isbn(?string $value): self
    {
        $this->instance->setIsbn($value);
        return $this;
    }

    /**
     * Sets ppid field.
     *
     * @param string|null $value
     */
    public function ppid(?string $value): self
    {
        $this->instance->setPpid($value);
        return $this;
    }

    /**
     * Sets duration field.
     *
     * @param float|null $value
     */
    public function duration(?float $value): self
    {
        $this->instance->setDuration($value);
        return $this;
    }

    /**
     * Sets tax field.
     *
     * @param float|null $value
     */
    public function tax(?float $value): self
    {
        $this->instance->setTax($value);
        return $this;
    }

    /**
     * Sets price field.
     *
     * @param float|null $value
     */
    public function price(?float $value): self
    {
        $this->instance->setPrice($value);
        return $this;
    }

    /**
     * Initializes a new Order Request Type Product object.
     */
    public function build(): OrderRequestTypeProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
