<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\Discount;
use PearsonSubscriptionsAPILib\Models\OverridesPricing;

/**
 * Builder for model OverridesPricing
 *
 * @see OverridesPricing
 */
class OverridesPricingBuilder
{
    /**
     * @var OverridesPricing
     */
    private $instance;

    private function __construct(OverridesPricing $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Overrides Pricing Builder object.
     */
    public static function init(): self
    {
        return new self(new OverridesPricing());
    }

    /**
     * Sets discount field.
     *
     * @param Discount|null $value
     */
    public function discount(?Discount $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Initializes a new Overrides Pricing object.
     */
    public function build(): OverridesPricing
    {
        return CoreHelper::clone($this->instance);
    }
}
