<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\RatePlanEndDate;

/**
 * Builder for model RatePlanEndDate
 *
 * @see RatePlanEndDate
 */
class RatePlanEndDateBuilder
{
    /**
     * @var RatePlanEndDate
     */
    private $instance;

    private function __construct(RatePlanEndDate $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Rate Plan End Date Builder object.
     */
    public static function init(): self
    {
        return new self(new RatePlanEndDate());
    }

    /**
     * Sets end Date Condition field.
     *
     * @param string|null $value
     */
    public function endDateCondition(?string $value): self
    {
        $this->instance->setEndDateCondition($value);
        return $this;
    }

    /**
     * Sets specific End Date field.
     *
     * @param \DateTime|null $value
     */
    public function specificEndDate(?\DateTime $value): self
    {
        $this->instance->setSpecificEndDate($value);
        return $this;
    }

    /**
     * Sets up To Periods field.
     *
     * @param float|null $value
     */
    public function upToPeriods(?float $value): self
    {
        $this->instance->setUpToPeriods($value);
        return $this;
    }

    /**
     * Sets up To Periods Type field.
     *
     * @param string|null $value
     */
    public function upToPeriodsType(?string $value): self
    {
        $this->instance->setUpToPeriodsType($value);
        return $this;
    }

    /**
     * Initializes a new Rate Plan End Date object.
     */
    public function build(): RatePlanEndDate
    {
        return CoreHelper::clone($this->instance);
    }
}
