<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\Discount;
use PplusSubscriptionPapiLib\Models\RatePlanPricing;
use PplusSubscriptionPapiLib\Models\RecurringFlatFee;

/**
 * Builder for model RatePlanPricing
 *
 * @see RatePlanPricing
 */
class RatePlanPricingBuilder
{
    /**
     * @var RatePlanPricing
     */
    private $instance;

    private function __construct(RatePlanPricing $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Rate Plan Pricing Builder object.
     */
    public static function init(): self
    {
        return new self(new RatePlanPricing());
    }

    /**
     * Sets discount field.
     *
     * @param Discount|null $value
     */
    public function discount(?Discount $value): self
    {
        $this->instance->setDiscount($value);
        return $this;
    }

    /**
     * Sets recurring Flat Fee field.
     *
     * @param RecurringFlatFee|null $value
     */
    public function recurringFlatFee(?RecurringFlatFee $value): self
    {
        $this->instance->setRecurringFlatFee($value);
        return $this;
    }

    /**
     * Initializes a new Rate Plan Pricing object.
     */
    public function build(): RatePlanPricing
    {
        return CoreHelper::clone($this->instance);
    }
}
