<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\RecurringFlatFee;

/**
 * Builder for model RecurringFlatFee
 *
 * @see RecurringFlatFee
 */
class RecurringFlatFeeBuilder
{
    /**
     * @var RecurringFlatFee
     */
    private $instance;

    private function __construct(RecurringFlatFee $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Recurring Flat Fee Builder object.
     */
    public static function init(): self
    {
        return new self(new RecurringFlatFee());
    }

    /**
     * Sets list Price field.
     *
     * @param float|null $value
     */
    public function listPrice(?float $value): self
    {
        $this->instance->setListPrice($value);
        return $this;
    }

    /**
     * Initializes a new Recurring Flat Fee object.
     */
    public function build(): RecurringFlatFee
    {
        return CoreHelper::clone($this->instance);
    }
}
