<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\RemoveProduct;

/**
 * Builder for model RemoveProduct
 *
 * @see RemoveProduct
 */
class RemoveProductBuilder
{
    /**
     * @var RemoveProduct
     */
    private $instance;

    private function __construct(RemoveProduct $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Remove Product Builder object.
     */
    public static function init(): self
    {
        return new self(new RemoveProduct());
    }

    /**
     * Sets product Rate Plan Id field.
     *
     * @param string|null $value
     */
    public function productRatePlanId(?string $value): self
    {
        $this->instance->setProductRatePlanId($value);
        return $this;
    }

    /**
     * Initializes a new Remove Product object.
     */
    public function build(): RemoveProduct
    {
        return CoreHelper::clone($this->instance);
    }
}
