<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\RenewalTerm;

/**
 * Builder for model RenewalTerm
 *
 * @see RenewalTerm
 */
class RenewalTermBuilder
{
    /**
     * @var RenewalTerm
     */
    private $instance;

    private function __construct(RenewalTerm $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Renewal Term Builder object.
     */
    public static function init(): self
    {
        return new self(new RenewalTerm());
    }

    /**
     * Sets period field.
     *
     * @param int|null $value
     */
    public function period(?int $value): self
    {
        $this->instance->setPeriod($value);
        return $this;
    }

    /**
     * Sets period Type field.
     *
     * @param string|null $value
     */
    public function periodType(?string $value): self
    {
        $this->instance->setPeriodType($value);
        return $this;
    }

    /**
     * Initializes a new Renewal Term object.
     */
    public function build(): RenewalTerm
    {
        return CoreHelper::clone($this->instance);
    }
}
