<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\SubscribeToRatePlan;
use PplusSubscriptionPapiLib\Models\SubscribeToRatePlansChargeOverride;

/**
 * Builder for model SubscribeToRatePlan
 *
 * @see SubscribeToRatePlan
 */
class SubscribeToRatePlanBuilder
{
    /**
     * @var SubscribeToRatePlan
     */
    private $instance;

    private function __construct(SubscribeToRatePlan $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Subscribe To Rate Plan Builder object.
     */
    public static function init(): self
    {
        return new self(new SubscribeToRatePlan());
    }

    /**
     * Sets product Rate Plan Id field.
     *
     * @param string|null $value
     */
    public function productRatePlanId(?string $value): self
    {
        $this->instance->setProductRatePlanId($value);
        return $this;
    }

    /**
     * Sets subscribe To Rate Plans Charge Overrides field.
     *
     * @param SubscribeToRatePlansChargeOverride[]|null $value
     */
    public function subscribeToRatePlansChargeOverrides(?array $value): self
    {
        $this->instance->setSubscribeToRatePlansChargeOverrides($value);
        return $this;
    }

    /**
     * Initializes a new Subscribe To Rate Plan object.
     */
    public function build(): SubscribeToRatePlan
    {
        return CoreHelper::clone($this->instance);
    }
}
