<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\TermsAndConditions;

/**
 * Builder for model TermsAndConditions
 *
 * @see TermsAndConditions
 */
class TermsAndConditionsBuilder
{
    /**
     * @var TermsAndConditions
     */
    private $instance;

    private function __construct(TermsAndConditions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terms And Conditions Builder object.
     */
    public static function init(): self
    {
        return new self(new TermsAndConditions());
    }

    /**
     * Sets autorenew field.
     *
     * @param bool|null $value
     */
    public function autorenew(?bool $value): self
    {
        $this->instance->setAutorenew($value);
        return $this;
    }

    /**
     * Initializes a new Terms And Conditions object.
     */
    public function build(): TermsAndConditions
    {
        return CoreHelper::clone($this->instance);
    }
}
