<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\InitialTerm;
use PearsonSubscriptionsAPILib\Models\RenewalTerm;
use PearsonSubscriptionsAPILib\Models\Terms;

/**
 * Builder for model Terms
 *
 * @see Terms
 */
class TermsBuilder
{
    /**
     * @var Terms
     */
    private $instance;

    private function __construct(Terms $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Terms Builder object.
     */
    public static function init(): self
    {
        return new self(new Terms());
    }

    /**
     * Sets initial Term field.
     *
     * @param InitialTerm|null $value
     */
    public function initialTerm(?InitialTerm $value): self
    {
        $this->instance->setInitialTerm($value);
        return $this;
    }

    /**
     * Sets renewal Terms field.
     *
     * @param RenewalTerm[]|null $value
     */
    public function renewalTerms(?array $value): self
    {
        $this->instance->setRenewalTerms($value);
        return $this;
    }

    /**
     * Sets renewal Setting field.
     *
     * @param string|null $value
     */
    public function renewalSetting(?string $value): self
    {
        $this->instance->setRenewalSetting($value);
        return $this;
    }

    /**
     * Sets auto Renew field.
     *
     * @param bool|null $value
     */
    public function autoRenew(?bool $value): self
    {
        $this->instance->setAutoRenew($value);
        return $this;
    }

    /**
     * Initializes a new Terms object.
     */
    public function build(): Terms
    {
        return CoreHelper::clone($this->instance);
    }
}
