<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\Account;
use PplusSubscriptionPapiLib\Models\CustomField;
use PplusSubscriptionPapiLib\Models\Product;
use PplusSubscriptionPapiLib\Models\UpdateSubscription;
use PplusSubscriptionPapiLib\Models\UpdateSubscriptionProcessingOptions;
use PplusSubscriptionPapiLib\Models\UpdateSubscriptionSubscription;

/**
 * Builder for model UpdateSubscription
 *
 * @see UpdateSubscription
 */
class UpdateSubscriptionBuilder
{
    /**
     * @var UpdateSubscription
     */
    private $instance;

    private function __construct(UpdateSubscription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Subscription Builder object.
     *
     * @param string $orderType
     */
    public static function init(string $orderType): self
    {
        return new self(new UpdateSubscription($orderType));
    }

    /**
     * Sets order Number field.
     *
     * @param string|null $value
     */
    public function orderNumber(?string $value): self
    {
        $this->instance->setOrderNumber($value);
        return $this;
    }

    /**
     * Sets order Date field.
     *
     * @param string|null $value
     */
    public function orderDate(?string $value): self
    {
        $this->instance->setOrderDate($value);
        return $this;
    }

    /**
     * Sets description field.
     *
     * @param string|null $value
     */
    public function description(?string $value): self
    {
        $this->instance->setDescription($value);
        return $this;
    }

    /**
     * Sets existing Account Number field.
     *
     * @param string|null $value
     */
    public function existingAccountNumber(?string $value): self
    {
        $this->instance->setExistingAccountNumber($value);
        return $this;
    }

    /**
     * Sets account field.
     *
     * @param Account|null $value
     */
    public function account(?Account $value): self
    {
        $this->instance->setAccount($value);
        return $this;
    }

    /**
     * Sets update Subscription Subscriptions field.
     *
     * @param UpdateSubscriptionSubscription[]|null $value
     */
    public function updateSubscriptionSubscriptions(?array $value): self
    {
        $this->instance->setUpdateSubscriptionSubscriptions($value);
        return $this;
    }

    /**
     * Sets update Subscription Processing Options field.
     *
     * @param UpdateSubscriptionProcessingOptions|null $value
     */
    public function updateSubscriptionProcessingOptions(?UpdateSubscriptionProcessingOptions $value): self
    {
        $this->instance->setUpdateSubscriptionProcessingOptions($value);
        return $this;
    }

    /**
     * Sets update Subscription Products field.
     *
     * @param Product[]|null $value
     */
    public function updateSubscriptionProducts(?array $value): self
    {
        $this->instance->setUpdateSubscriptionProducts($value);
        return $this;
    }

    /**
     * Sets custom Fields field.
     *
     * @param CustomField[]|null $value
     */
    public function customFields(?array $value): self
    {
        $this->instance->setCustomFields($value);
        return $this;
    }

    /**
     * Sets payment Capture field.
     *
     * @param array|null $value
     */
    public function paymentCapture(?array $value): self
    {
        $this->instance->setPaymentCapture($value);
        return $this;
    }

    /**
     * Initializes a new Update Subscription object.
     */
    public function build(): UpdateSubscription
    {
        return CoreHelper::clone($this->instance);
    }
}
