<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models\Builders;

use Core\Utils\CoreHelper;
use PearsonSubscriptionsAPILib\Models\UpdateOrderOrderAction;
use PearsonSubscriptionsAPILib\Models\UpdateSubscriptionSubscription;

/**
 * Builder for model UpdateSubscriptionSubscription
 *
 * @see UpdateSubscriptionSubscription
 */
class UpdateSubscriptionSubscriptionBuilder
{
    /**
     * @var UpdateSubscriptionSubscription
     */
    private $instance;

    private function __construct(UpdateSubscriptionSubscription $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Subscription Subscription Builder object.
     *
     * @param string $subscriptionNumber
     */
    public static function init(string $subscriptionNumber): self
    {
        return new self(new UpdateSubscriptionSubscription($subscriptionNumber));
    }

    /**
     * Sets order Actions field.
     *
     * @param UpdateOrderOrderAction[]|null $value
     */
    public function orderActions(?array $value): self
    {
        $this->instance->setOrderActions($value);
        return $this;
    }

    /**
     * Initializes a new Update Subscription Subscription object.
     */
    public function build(): UpdateSubscriptionSubscription
    {
        return CoreHelper::clone($this->instance);
    }
}
