<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\UpdateSubscriptionProcessingOptions;

/**
 * Builder for model UpdateSubscriptionProcessingOptions
 *
 * @see UpdateSubscriptionProcessingOptions
 */
class UpdateSubscriptionProcessingOptionsBuilder
{
    /**
     * @var UpdateSubscriptionProcessingOptions
     */
    private $instance;

    private function __construct(UpdateSubscriptionProcessingOptions $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Subscription Processing Options Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateSubscriptionProcessingOptions());
    }

    /**
     * Sets run Billing field.
     *
     * @param bool|null $value
     */
    public function runBilling(?bool $value): self
    {
        $this->instance->setRunBilling($value);
        return $this;
    }

    /**
     * Sets collect Payment field.
     *
     * @param bool|null $value
     */
    public function collectPayment(?bool $value): self
    {
        $this->instance->setCollectPayment($value);
        return $this;
    }

    /**
     * Initializes a new Update Subscription Processing Options object.
     */
    public function build(): UpdateSubscriptionProcessingOptions
    {
        return CoreHelper::clone($this->instance);
    }
}
