<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\AddProduct;
use PplusSubscriptionPapiLib\Models\RemoveProduct;
use PplusSubscriptionPapiLib\Models\TermsAndConditions;
use PplusSubscriptionPapiLib\Models\TriggerDate;
use PplusSubscriptionPapiLib\Models\UpdateOrderOrderAction;

/**
 * Builder for model UpdateOrderOrderAction
 *
 * @see UpdateOrderOrderAction
 */
class UpdateOrderOrderActionBuilder
{
    /**
     * @var UpdateOrderOrderAction
     */
    private $instance;

    private function __construct(UpdateOrderOrderAction $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Order Order Action Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateOrderOrderAction());
    }

    /**
     * Sets trigger Dates field.
     *
     * @param TriggerDate[]|null $value
     */
    public function triggerDates(?array $value): self
    {
        $this->instance->setTriggerDates($value);
        return $this;
    }

    /**
     * Sets add Product field.
     *
     * @param AddProduct|null $value
     */
    public function addProduct(?AddProduct $value): self
    {
        $this->instance->setAddProduct($value);
        return $this;
    }

    /**
     * Sets remove Product field.
     *
     * @param RemoveProduct|null $value
     */
    public function removeProduct(?RemoveProduct $value): self
    {
        $this->instance->setRemoveProduct($value);
        return $this;
    }

    /**
     * Sets terms And Conditions field.
     *
     * @param TermsAndConditions|null $value
     */
    public function termsAndConditions(?TermsAndConditions $value): self
    {
        $this->instance->setTermsAndConditions($value);
        return $this;
    }

    /**
     * Initializes a new Update Order Order Action object.
     */
    public function build(): UpdateOrderOrderAction
    {
        return CoreHelper::clone($this->instance);
    }
}
