<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models\Builders;

use Core\Utils\CoreHelper;
use PplusSubscriptionPapiLib\Models\AddProductEndDate;
use PplusSubscriptionPapiLib\Models\CustomerFacingCustomFields;
use PplusSubscriptionPapiLib\Models\OverridesPricing;
use PplusSubscriptionPapiLib\Models\UpdateOrAddProductChargeOverride;

/**
 * Builder for model UpdateOrAddProductChargeOverride
 *
 * @see UpdateOrAddProductChargeOverride
 */
class UpdateOrAddProductChargeOverrideBuilder
{
    /**
     * @var UpdateOrAddProductChargeOverride
     */
    private $instance;

    private function __construct(UpdateOrAddProductChargeOverride $instance)
    {
        $this->instance = $instance;
    }

    /**
     * Initializes a new Update Or Add Product Charge Override Builder object.
     */
    public static function init(): self
    {
        return new self(new UpdateOrAddProductChargeOverride());
    }

    /**
     * Sets product Rate Plan Charge Id field.
     *
     * @param string|null $value
     */
    public function productRatePlanChargeId(?string $value): self
    {
        $this->instance->setProductRatePlanChargeId($value);
        return $this;
    }

    /**
     * Sets customer Facing Custom Fields field.
     *
     * @param CustomerFacingCustomFields|null $value
     */
    public function customerFacingCustomFields(?CustomerFacingCustomFields $value): self
    {
        $this->instance->setCustomerFacingCustomFields($value);
        return $this;
    }

    /**
     * Sets overrides Pricing field.
     *
     * @param OverridesPricing|null $value
     */
    public function overridesPricing(?OverridesPricing $value): self
    {
        $this->instance->setOverridesPricing($value);
        return $this;
    }

    /**
     * Sets add Product End Date field.
     *
     * @param AddProductEndDate|null $value
     */
    public function addProductEndDate(?AddProductEndDate $value): self
    {
        $this->instance->setAddProductEndDate($value);
        return $this;
    }

    /**
     * Initializes a new Update Or Add Product Charge Override object.
     */
    public function build(): UpdateOrAddProductChargeOverride
    {
        return CoreHelper::clone($this->instance);
    }
}
