<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Controllers;

use CoreInterfaces\Core\Request\RequestMethod;
use PearsonSubscriptionsAPILib\Exceptions\ApiException;

class HealthController extends BaseController
{
    /**
     * @return mixed Response from the API call
     *
     * @throws ApiException Thrown if API call fails
     */
    public function healthCheck()
    {
        $_reqBuilder = $this->requestBuilder(RequestMethod::GET, '/health-check');

        return $this->execute($_reqBuilder);
    }
}
