<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Exceptions;

use PearsonSubscriptionsAPILib\ApiHelper;

class AuthErrorTypeException extends ApiException
{
    /**
     * @var \PearsonSubscriptionsAPILib\Models\AuthError|null
     */
    private $authError;

    /**
     * Returns Auth Error.
     */
    public function getAuthError(): ?\PearsonSubscriptionsAPILib\Models\AuthError
    {
        return $this->authError;
    }

    /**
     * Sets Auth Error.
     *
     * @maps authError
     */
    public function setAuthError(?\PearsonSubscriptionsAPILib\Models\AuthError $authError): void
    {
        $this->authError = $authError;
    }

    /**
     * Converts the AuthErrorTypeException object to a human-readable string representation.
     *
     * @return string The string representation of the AuthErrorTypeException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AuthErrorTypeException',
            ['authError' => $this->authError],
            parent::__toString()
        );
    }
}
