<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Exceptions;

use PplusSubscriptionPapiLib\ApiHelper;

class OrderRespTypeErrorException extends ApiException
{
    /**
     * @var string|null
     */
    private $orderNumber;

    /**
     * @var string|null
     */
    private $subscriptionId;

    /**
     * @var \PplusSubscriptionPapiLib\Models\OrderRespError|null
     */
    private $orderRespError;

    /**
     * Returns Order Number.
     * Order Number.
     */
    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    /**
     * Sets Order Number.
     * Order Number.
     *
     * @maps orderNumber
     */
    public function setOrderNumber(?string $orderNumber): void
    {
        $this->orderNumber = $orderNumber;
    }

    /**
     * Returns Subscription Id.
     * Pearson subscription id.
     */
    public function getSubscriptionId(): ?string
    {
        return $this->subscriptionId;
    }

    /**
     * Sets Subscription Id.
     * Pearson subscription id.
     *
     * @maps subscriptionId
     */
    public function setSubscriptionId(?string $subscriptionId): void
    {
        $this->subscriptionId = $subscriptionId;
    }

    /**
     * Returns Order Resp Error.
     */
    public function getOrderRespError(): ?\PplusSubscriptionPapiLib\Models\OrderRespError
    {
        return $this->orderRespError;
    }

    /**
     * Sets Order Resp Error.
     *
     * @maps orderRespError
     */
    public function setOrderRespError(?\PplusSubscriptionPapiLib\Models\OrderRespError $orderRespError): void
    {
        $this->orderRespError = $orderRespError;
    }

    /**
     * Converts the OrderRespTypeErrorException object to a human-readable string representation.
     *
     * @return string The string representation of the OrderRespTypeErrorException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrderRespTypeErrorException',
            [
                'orderNumber' => $this->orderNumber,
                'subscriptionId' => $this->subscriptionId,
                'orderRespError' => $this->orderRespError
            ],
            parent::__toString()
        );
    }
}
