<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Exceptions;

use PplusSubscriptionPapiLib\ApiHelper;

class OrderErrorTypeException extends ApiException
{
    /**
     * @var string|null
     */
    private $orderNumber;

    /**
     * @var \PplusSubscriptionPapiLib\Models\OrderError|null
     */
    private $orderError;

    /**
     * Returns Order Number.
     * Order Number.
     */
    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    /**
     * Sets Order Number.
     * Order Number.
     *
     * @maps orderNumber
     */
    public function setOrderNumber(?string $orderNumber): void
    {
        $this->orderNumber = $orderNumber;
    }

    /**
     * Returns Order Error.
     */
    public function getOrderError(): ?\PplusSubscriptionPapiLib\Models\OrderError
    {
        return $this->orderError;
    }

    /**
     * Sets Order Error.
     *
     * @maps orderError
     */
    public function setOrderError(?\PplusSubscriptionPapiLib\Models\OrderError $orderError): void
    {
        $this->orderError = $orderError;
    }

    /**
     * Converts the OrderErrorTypeException object to a human-readable string representation.
     *
     * @return string The string representation of the OrderErrorTypeException object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrderErrorTypeException',
            ['orderNumber' => $this->orderNumber, 'orderError' => $this->orderError],
            parent::__toString()
        );
    }
}
