<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class AddProductEndDate implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $endDateCondition;

    /**
     * @var string|null
     */
    private $specificEndDate;

    /**
     * @var float|null
     */
    private $upToPeriods;

    /**
     * @var string|null
     */
    private $upToPeriodsType;

    /**
     * Returns End Date Condition.
     * enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"
     */
    public function getEndDateCondition(): ?string
    {
        return $this->endDateCondition;
    }

    /**
     * Sets End Date Condition.
     * enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"
     *
     * @maps endDateCondition
     * @factory \PplusSubscriptionPapiLib\Models\EndDateConditionEnum::checkValue
     */
    public function setEndDateCondition(?string $endDateCondition): void
    {
        $this->endDateCondition = $endDateCondition;
    }

    /**
     * Returns Specific End Date.
     */
    public function getSpecificEndDate(): ?string
    {
        return $this->specificEndDate;
    }

    /**
     * Sets Specific End Date.
     *
     * @maps specificEndDate
     */
    public function setSpecificEndDate(?string $specificEndDate): void
    {
        $this->specificEndDate = $specificEndDate;
    }

    /**
     * Returns Up to Periods.
     */
    public function getUpToPeriods(): ?float
    {
        return $this->upToPeriods;
    }

    /**
     * Sets Up to Periods.
     *
     * @maps upToPeriods
     */
    public function setUpToPeriods(?float $upToPeriods): void
    {
        $this->upToPeriods = $upToPeriods;
    }

    /**
     * Returns Up to Periods Type.
     */
    public function getUpToPeriodsType(): ?string
    {
        return $this->upToPeriodsType;
    }

    /**
     * Sets Up to Periods Type.
     *
     * @maps upToPeriodsType
     */
    public function setUpToPeriodsType(?string $upToPeriodsType): void
    {
        $this->upToPeriodsType = $upToPeriodsType;
    }

    /**
     * Converts the AddProductEndDate object to a human-readable string representation.
     *
     * @return string The string representation of the AddProductEndDate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AddProductEndDate',
            [
                'endDateCondition' => $this->endDateCondition,
                'specificEndDate' => $this->specificEndDate,
                'upToPeriods' => $this->upToPeriods,
                'upToPeriodsType' => $this->upToPeriodsType
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->endDateCondition)) {
            $json['endDateCondition'] = EndDateConditionEnum::checkValue($this->endDateCondition);
        }
        if (isset($this->specificEndDate)) {
            $json['specificEndDate']  = $this->specificEndDate;
        }
        if (isset($this->upToPeriods)) {
            $json['upToPeriods']      = $this->upToPeriods;
        }
        if (isset($this->upToPeriodsType)) {
            $json['upToPeriodsType']  = $this->upToPeriodsType;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
