<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

/**
 * Information about an order action of type `addProduct`.
 *
 * If you want to create a pending order through the "Add product" order action, and if the charge's
 * trigger condition is `Specific Date`, you must set a charge number in the `chargeNumber` field for
 * the "Add product" order action.
 */
class AddProduct implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $productRatePlanId;

    /**
     * @var UpdateOrAddProductChargeOverride[]|null
     */
    private $updateOrAddProductChargeOverrides;

    /**
     * Returns Product Rate Plan Id.
     * Internal identifier of the product rate plan that the rate plan is based on.
     */
    public function getProductRatePlanId(): ?string
    {
        return $this->productRatePlanId;
    }

    /**
     * Sets Product Rate Plan Id.
     * Internal identifier of the product rate plan that the rate plan is based on.
     *
     * @maps productRatePlanId
     */
    public function setProductRatePlanId(?string $productRatePlanId): void
    {
        $this->productRatePlanId = $productRatePlanId;
    }

    /**
     * Returns Update or Add Product Charge Overrides.
     *
     * @return UpdateOrAddProductChargeOverride[]|null
     */
    public function getUpdateOrAddProductChargeOverrides(): ?array
    {
        return $this->updateOrAddProductChargeOverrides;
    }

    /**
     * Sets Update or Add Product Charge Overrides.
     *
     * @maps updateOrAddProductChargeOverrides
     *
     * @param UpdateOrAddProductChargeOverride[]|null $updateOrAddProductChargeOverrides
     */
    public function setUpdateOrAddProductChargeOverrides(?array $updateOrAddProductChargeOverrides): void
    {
        $this->updateOrAddProductChargeOverrides = $updateOrAddProductChargeOverrides;
    }

    /**
     * Converts the AddProduct object to a human-readable string representation.
     *
     * @return string The string representation of the AddProduct object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'AddProduct',
            [
                'productRatePlanId' => $this->productRatePlanId,
                'updateOrAddProductChargeOverrides' => $this->updateOrAddProductChargeOverrides
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->productRatePlanId)) {
            $json['productRatePlanId']                 = $this->productRatePlanId;
        }
        if (isset($this->updateOrAddProductChargeOverrides)) {
            $json['updateOrAddProductChargeOverrides'] = $this->updateOrAddProductChargeOverrides;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
