<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class CancelResType implements \JsonSerializable
{
    /**
     * @var string
     */
    private $message;

    /**
     * @param string $message
     */
    public function __construct(string $message)
    {
        $this->message = $message;
    }

    /**
     * Returns Message.
     * Response Message
     */
    public function getMessage(): string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * Response Message
     *
     * @required
     * @maps message
     */
    public function setMessage(string $message): void
    {
        $this->message = $message;
    }

    /**
     * Converts the CancelResType object to a human-readable string representation.
     *
     * @return string The string representation of the CancelResType object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CancelResType', ['message' => $this->message]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['message'] = $this->message;

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
