<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

/**
 * Information about an order action of type `CreateSubscription`.
 */
class CreateSubscription implements \JsonSerializable
{
    /**
     * @var Terms|null
     */
    private $terms;

    /**
     * @var SubscribeToRatePlan[]|null
     */
    private $subscribeToRatePlans;

    /**
     * Returns Terms.
     * Container for the terms and renewal settings of the subscription.
     */
    public function getTerms(): ?Terms
    {
        return $this->terms;
    }

    /**
     * Sets Terms.
     * Container for the terms and renewal settings of the subscription.
     *
     * @maps terms
     */
    public function setTerms(?Terms $terms): void
    {
        $this->terms = $terms;
    }

    /**
     * Returns Subscribe to Rate Plans.
     *
     * @return SubscribeToRatePlan[]|null
     */
    public function getSubscribeToRatePlans(): ?array
    {
        return $this->subscribeToRatePlans;
    }

    /**
     * Sets Subscribe to Rate Plans.
     *
     * @maps subscribeToRatePlans
     *
     * @param SubscribeToRatePlan[]|null $subscribeToRatePlans
     */
    public function setSubscribeToRatePlans(?array $subscribeToRatePlans): void
    {
        $this->subscribeToRatePlans = $subscribeToRatePlans;
    }

    /**
     * Converts the CreateSubscription object to a human-readable string representation.
     *
     * @return string The string representation of the CreateSubscription object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateSubscription',
            ['terms' => $this->terms, 'subscribeToRatePlans' => $this->subscribeToRatePlans]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->terms)) {
            $json['terms']                = $this->terms;
        }
        if (isset($this->subscribeToRatePlans)) {
            $json['subscribeToRatePlans'] = $this->subscribeToRatePlans;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
