<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class CreateOrderOrderAction implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $type;

    /**
     * @var TriggerDate[]|null
     */
    private $triggerDates;

    /**
     * @var CreateSubscription|null
     */
    private $createSubscription;

    /**
     * Returns Type.
     */
    public function getType(): ?string
    {
        return $this->type;
    }

    /**
     * Sets Type.
     *
     * @maps type
     * @factory \PplusSubscriptionPapiLib\Models\TypeEnum::checkValue
     */
    public function setType(?string $type): void
    {
        $this->type = $type;
    }

    /**
     * Returns Trigger Dates.
     *
     * @return TriggerDate[]|null
     */
    public function getTriggerDates(): ?array
    {
        return $this->triggerDates;
    }

    /**
     * Sets Trigger Dates.
     *
     * @maps triggerDates
     *
     * @param TriggerDate[]|null $triggerDates
     */
    public function setTriggerDates(?array $triggerDates): void
    {
        $this->triggerDates = $triggerDates;
    }

    /**
     * Returns Create Subscription.
     * Information about an order action of type `CreateSubscription`.
     */
    public function getCreateSubscription(): ?CreateSubscription
    {
        return $this->createSubscription;
    }

    /**
     * Sets Create Subscription.
     * Information about an order action of type `CreateSubscription`.
     *
     * @maps createSubscription
     */
    public function setCreateSubscription(?CreateSubscription $createSubscription): void
    {
        $this->createSubscription = $createSubscription;
    }

    /**
     * Converts the CreateOrderOrderAction object to a human-readable string representation.
     *
     * @return string The string representation of the CreateOrderOrderAction object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'CreateOrderOrderAction',
            [
                'type' => $this->type,
                'triggerDates' => $this->triggerDates,
                'createSubscription' => $this->createSubscription
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->type)) {
            $json['type']               = TypeEnum::checkValue($this->type);
        }
        if (isset($this->triggerDates)) {
            $json['triggerDates']       = $this->triggerDates;
        }
        if (isset($this->createSubscription)) {
            $json['createSubscription'] = $this->createSubscription;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
