<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class CustomerFacingCustomFields implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $customerFacingC;

    /**
     * Returns Customer Facing C.
     */
    public function getCustomerFacingC(): ?string
    {
        return $this->customerFacingC;
    }

    /**
     * Sets Customer Facing C.
     *
     * @maps customerFacing__c
     */
    public function setCustomerFacingC(?string $customerFacingC): void
    {
        $this->customerFacingC = $customerFacingC;
    }

    /**
     * Converts the CustomerFacingCustomFields object to a human-readable string representation.
     *
     * @return string The string representation of the CustomerFacingCustomFields object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('CustomerFacingCustomFields', ['customerFacingC' => $this->customerFacingC]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->customerFacingC)) {
            $json['customerFacing__c'] = $this->customerFacingC;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
