<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class Discount implements \JsonSerializable
{
    /**
     * @var float|null
     */
    private $discountAmount;

    /**
     * @var float|null
     */
    private $discountPercentage;

    /**
     * Returns Discount Amount.
     * Only applicable if the discount charge is a fixed-amount discount.
     */
    public function getDiscountAmount(): ?float
    {
        return $this->discountAmount;
    }

    /**
     * Sets Discount Amount.
     * Only applicable if the discount charge is a fixed-amount discount.
     *
     * @maps discountAmount
     */
    public function setDiscountAmount(?float $discountAmount): void
    {
        $this->discountAmount = $discountAmount;
    }

    /**
     * Returns Discount Percentage.
     * Only applicable if the discount charge is a percentage discount
     */
    public function getDiscountPercentage(): ?float
    {
        return $this->discountPercentage;
    }

    /**
     * Sets Discount Percentage.
     * Only applicable if the discount charge is a percentage discount
     *
     * @maps discountPercentage
     */
    public function setDiscountPercentage(?float $discountPercentage): void
    {
        $this->discountPercentage = $discountPercentage;
    }

    /**
     * Converts the Discount object to a human-readable string representation.
     *
     * @return string The string representation of the Discount object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'Discount',
            ['discountAmount' => $this->discountAmount, 'discountPercentage' => $this->discountPercentage]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->discountAmount)) {
            $json['discountAmount']     = $this->discountAmount;
        }
        if (isset($this->discountPercentage)) {
            $json['discountPercentage'] = $this->discountPercentage;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
