<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"
 */
class EndDateConditionEnum
{
    public const SUBSCRIPTION_END = 'Subscription_End';

    public const FIXED_PERIOD = 'Fixed_Period';

    public const SPECIFIC_END_DATE = 'Specific_End_Date';

    private const _ALL_VALUES = [self::SUBSCRIPTION_END, self::FIXED_PERIOD, self::SPECIFIC_END_DATE];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for EndDateConditionEnum.");
    }
}
