<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use PearsonSubscriptionsAPILib\ApiHelper;
use stdClass;

class OrderRespType implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $message;

    /**
     * @var string|null
     */
    private $orderNumber;

    /**
     * @var string|null
     */
    private $subscriptionNumber;

    /**
     * Returns Message.
     * message description once subscription creation is sucess.
     */
    public function getMessage(): ?string
    {
        return $this->message;
    }

    /**
     * Sets Message.
     * message description once subscription creation is sucess.
     *
     * @maps message
     */
    public function setMessage(?string $message): void
    {
        $this->message = $message;
    }

    /**
     * Returns Order Number.
     * order number.
     */
    public function getOrderNumber(): ?string
    {
        return $this->orderNumber;
    }

    /**
     * Sets Order Number.
     * order number.
     *
     * @maps orderNumber
     */
    public function setOrderNumber(?string $orderNumber): void
    {
        $this->orderNumber = $orderNumber;
    }

    /**
     * Returns Subscription Number.
     * subscription id.
     */
    public function getSubscriptionNumber(): ?string
    {
        return $this->subscriptionNumber;
    }

    /**
     * Sets Subscription Number.
     * subscription id.
     *
     * @maps subscriptionNumber
     */
    public function setSubscriptionNumber(?string $subscriptionNumber): void
    {
        $this->subscriptionNumber = $subscriptionNumber;
    }

    /**
     * Converts the OrderRespType object to a human-readable string representation.
     *
     * @return string The string representation of the OrderRespType object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'OrderRespType',
            [
                'message' => $this->message,
                'orderNumber' => $this->orderNumber,
                'subscriptionNumber' => $this->subscriptionNumber
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->message)) {
            $json['message']            = $this->message;
        }
        if (isset($this->orderNumber)) {
            $json['orderNumber']        = $this->orderNumber;
        }
        if (isset($this->subscriptionNumber)) {
            $json['subscriptionNumber'] = $this->subscriptionNumber;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
