<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Order Type .
 */
class OrderTypeEnum
{
    public const UPGRADE = 'UPGRADE';

    public const DOWNGRADE = 'DOWNGRADE';

    public const RENEWON = 'RENEWON';

    public const RENEWOFF = 'RENEWOFF';

    public const MIBUPGRADE = 'MIBUPGRADE';

    public const MIBRENEWON = 'MIBRENEWON';

    public const MIBRENEWOFF = 'MIBRENEWOFF';

    private const _ALL_VALUES = [
        self::UPGRADE,
        self::DOWNGRADE,
        self::RENEWON,
        self::RENEWOFF,
        self::MIBUPGRADE,
        self::MIBRENEWON,
        self::MIBRENEWOFF
    ];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for OrderTypeEnum.");
    }
}
