<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use PearsonSubscriptionsAPILib\ApiHelper;
use stdClass;

class OverridesPricing implements \JsonSerializable
{
    /**
     * @var Discount|null
     */
    private $discount;

    /**
     * Returns Discount.
     */
    public function getDiscount(): ?Discount
    {
        return $this->discount;
    }

    /**
     * Sets Discount.
     *
     * @maps discount
     */
    public function setDiscount(?Discount $discount): void
    {
        $this->discount = $discount;
    }

    /**
     * Converts the OverridesPricing object to a human-readable string representation.
     *
     * @return string The string representation of the OverridesPricing object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('OverridesPricing', ['discount' => $this->discount]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->discount)) {
            $json['discount'] = $this->discount;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
