<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use PearsonSubscriptionsAPILib\ApiHelper;
use PearsonSubscriptionsAPILib\Utils\DateTimeHelper;
use stdClass;

class RatePlanEndDate implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $endDateCondition;

    /**
     * @var \DateTime|null
     */
    private $specificEndDate;

    /**
     * @var float|null
     */
    private $upToPeriods;

    /**
     * @var string|null
     */
    private $upToPeriodsType;

    /**
     * Returns End Date Condition.
     * enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"
     */
    public function getEndDateCondition(): ?string
    {
        return $this->endDateCondition;
    }

    /**
     * Sets End Date Condition.
     * enum values are "Subscription_End" "Fixed_Period" "Specific_End_Date"
     *
     * @maps endDateCondition
     * @factory \PearsonSubscriptionsAPILib\Models\EndDateConditionEnum::checkValue
     */
    public function setEndDateCondition(?string $endDateCondition): void
    {
        $this->endDateCondition = $endDateCondition;
    }

    /**
     * Returns Specific End Date.
     */
    public function getSpecificEndDate(): ?\DateTime
    {
        return $this->specificEndDate;
    }

    /**
     * Sets Specific End Date.
     *
     * @maps specificEndDate
     * @factory \PearsonSubscriptionsAPILib\Utils\DateTimeHelper::fromSimpleDate
     */
    public function setSpecificEndDate(?\DateTime $specificEndDate): void
    {
        $this->specificEndDate = $specificEndDate;
    }

    /**
     * Returns Up to Periods.
     * Duration of the charge in billing periods, days, weeks, months, or years, depending on the value of
     * the upToPeriodsType field. Only applicable if the value of the endDateCondition field is
     * Fixed_Period.
     */
    public function getUpToPeriods(): ?float
    {
        return $this->upToPeriods;
    }

    /**
     * Sets Up to Periods.
     * Duration of the charge in billing periods, days, weeks, months, or years, depending on the value of
     * the upToPeriodsType field. Only applicable if the value of the endDateCondition field is
     * Fixed_Period.
     *
     * @maps upToPeriods
     */
    public function setUpToPeriods(?float $upToPeriods): void
    {
        $this->upToPeriods = $upToPeriods;
    }

    /**
     * Returns Up to Periods Type.
     * Unit of time that the charge duration is measured in. Only applicable if the value of the
     * endDateCondition field is Fixed_Period.
     */
    public function getUpToPeriodsType(): ?string
    {
        return $this->upToPeriodsType;
    }

    /**
     * Sets Up to Periods Type.
     * Unit of time that the charge duration is measured in. Only applicable if the value of the
     * endDateCondition field is Fixed_Period.
     *
     * @maps upToPeriodsType
     * @factory \PearsonSubscriptionsAPILib\Models\UpToPeriodsTypeEnum::checkValue
     */
    public function setUpToPeriodsType(?string $upToPeriodsType): void
    {
        $this->upToPeriodsType = $upToPeriodsType;
    }

    /**
     * Converts the RatePlanEndDate object to a human-readable string representation.
     *
     * @return string The string representation of the RatePlanEndDate object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'RatePlanEndDate',
            [
                'endDateCondition' => $this->endDateCondition,
                'specificEndDate' => $this->specificEndDate,
                'upToPeriods' => $this->upToPeriods,
                'upToPeriodsType' => $this->upToPeriodsType
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->endDateCondition)) {
            $json['endDateCondition'] = EndDateConditionEnum::checkValue($this->endDateCondition);
        }
        if (isset($this->specificEndDate)) {
            $json['specificEndDate']  = DateTimeHelper::toSimpleDate($this->specificEndDate);
        }
        if (isset($this->upToPeriods)) {
            $json['upToPeriods']      = $this->upToPeriods;
        }
        if (isset($this->upToPeriodsType)) {
            $json['upToPeriodsType']  = UpToPeriodsTypeEnum::checkValue($this->upToPeriodsType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
