<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

/**
 * Remove product details from the subscription plan
 */
class RemoveProduct implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $productRatePlanId;

    /**
     * Returns Product Rate Plan Id.
     * Internal identifier of the product rate plan that the rate plan is based on.
     */
    public function getProductRatePlanId(): ?string
    {
        return $this->productRatePlanId;
    }

    /**
     * Sets Product Rate Plan Id.
     * Internal identifier of the product rate plan that the rate plan is based on.
     *
     * @maps productRatePlanId
     */
    public function setProductRatePlanId(?string $productRatePlanId): void
    {
        $this->productRatePlanId = $productRatePlanId;
    }

    /**
     * Converts the RemoveProduct object to a human-readable string representation.
     *
     * @return string The string representation of the RemoveProduct object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('RemoveProduct', ['productRatePlanId' => $this->productRatePlanId]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->productRatePlanId)) {
            $json['productRatePlanId'] = $this->productRatePlanId;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
