<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class RenewalTerm implements \JsonSerializable
{
    /**
     * @var int|null
     */
    private $period;

    /**
     * @var string|null
     */
    private $periodType;

    /**
     * Returns Period.
     * Duration of the renewal term in months, years, days, or weeks, depending on the value of the
     * `periodType` field.
     */
    public function getPeriod(): ?int
    {
        return $this->period;
    }

    /**
     * Sets Period.
     * Duration of the renewal term in months, years, days, or weeks, depending on the value of the
     * `periodType` field.
     *
     * @maps period
     */
    public function setPeriod(?int $period): void
    {
        $this->period = $period;
    }

    /**
     * Returns Period Type.
     * Unit of time that the renewal term is measured in.
     */
    public function getPeriodType(): ?string
    {
        return $this->periodType;
    }

    /**
     * Sets Period Type.
     * Unit of time that the renewal term is measured in.
     *
     * @maps periodType
     * @factory \PplusSubscriptionPapiLib\Models\PeriodTypeEnum::checkValue
     */
    public function setPeriodType(?string $periodType): void
    {
        $this->periodType = $periodType;
    }

    /**
     * Converts the RenewalTerm object to a human-readable string representation.
     *
     * @return string The string representation of the RenewalTerm object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify('RenewalTerm', ['period' => $this->period, 'periodType' => $this->periodType]);
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->period)) {
            $json['period']     = $this->period;
        }
        if (isset($this->periodType)) {
            $json['periodType'] = PeriodTypeEnum::checkValue($this->periodType);
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
