<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class SubscribeToRatePlan implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $productRatePlanId;

    /**
     * @var SubscribeToRatePlansChargeOverride[]|null
     */
    private $subscribeToRatePlansChargeOverrides;

    /**
     * Returns Product Rate Plan Id.
     * This is unique Product Rate Plan id which signifies the subscription type,entitlementLevel,
     * maxEntitlements,numEntitlements etc.
     */
    public function getProductRatePlanId(): ?string
    {
        return $this->productRatePlanId;
    }

    /**
     * Sets Product Rate Plan Id.
     * This is unique Product Rate Plan id which signifies the subscription type,entitlementLevel,
     * maxEntitlements,numEntitlements etc.
     *
     * @maps productRatePlanId
     */
    public function setProductRatePlanId(?string $productRatePlanId): void
    {
        $this->productRatePlanId = $productRatePlanId;
    }

    /**
     * Returns Subscribe to Rate Plans Charge Overrides.
     *
     * @return SubscribeToRatePlansChargeOverride[]|null
     */
    public function getSubscribeToRatePlansChargeOverrides(): ?array
    {
        return $this->subscribeToRatePlansChargeOverrides;
    }

    /**
     * Sets Subscribe to Rate Plans Charge Overrides.
     *
     * @maps subscribeToRatePlansChargeOverrides
     *
     * @param SubscribeToRatePlansChargeOverride[]|null $subscribeToRatePlansChargeOverrides
     */
    public function setSubscribeToRatePlansChargeOverrides(?array $subscribeToRatePlansChargeOverrides): void
    {
        $this->subscribeToRatePlansChargeOverrides = $subscribeToRatePlansChargeOverrides;
    }

    /**
     * Converts the SubscribeToRatePlan object to a human-readable string representation.
     *
     * @return string The string representation of the SubscribeToRatePlan object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'SubscribeToRatePlan',
            [
                'productRatePlanId' => $this->productRatePlanId,
                'subscribeToRatePlansChargeOverrides' => $this->subscribeToRatePlansChargeOverrides
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->productRatePlanId)) {
            $json['productRatePlanId']                   = $this->productRatePlanId;
        }
        if (isset($this->subscribeToRatePlansChargeOverrides)) {
            $json['subscribeToRatePlansChargeOverrides'] = $this->subscribeToRatePlansChargeOverrides;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
