<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Type of the first term. If the value of this field is `TERMED`, the first term has a predefined
 * duration based on the value of the `period` field. If the value of this field is `EVERGREEN`, the
 * first term does not have a predefined duration.
 */
class TermTypeEnum
{
    public const TERMED = 'TERMED';

    public const EVERGREEN = 'EVERGREEN';

    private const _ALL_VALUES = [self::TERMED, self::EVERGREEN];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for TermTypeEnum.");
    }
}
