<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use PearsonSubscriptionsAPILib\ApiHelper;
use stdClass;

class UpdateSubscriptionSubscription implements \JsonSerializable
{
    /**
     * @var string
     */
    private $subscriptionNumber;

    /**
     * @var UpdateOrderOrderAction[]|null
     */
    private $orderActions;

    /**
     * @param string $subscriptionNumber
     */
    public function __construct(string $subscriptionNumber)
    {
        $this->subscriptionNumber = $subscriptionNumber;
    }

    /**
     * Returns Subscription Number.
     * Subscription number or ID. Subscription status must be active for the same.
     */
    public function getSubscriptionNumber(): string
    {
        return $this->subscriptionNumber;
    }

    /**
     * Sets Subscription Number.
     * Subscription number or ID. Subscription status must be active for the same.
     *
     * @required
     * @maps subscriptionNumber
     */
    public function setSubscriptionNumber(string $subscriptionNumber): void
    {
        $this->subscriptionNumber = $subscriptionNumber;
    }

    /**
     * Returns Order Actions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence when
     * it was provided in the request.
     *
     * @return UpdateOrderOrderAction[]|null
     */
    public function getOrderActions(): ?array
    {
        return $this->orderActions;
    }

    /**
     * Sets Order Actions.
     * The actions to be applied to the subscription. Order actions will be stored with the sequence when
     * it was provided in the request.
     *
     * @maps orderActions
     *
     * @param UpdateOrderOrderAction[]|null $orderActions
     */
    public function setOrderActions(?array $orderActions): void
    {
        $this->orderActions = $orderActions;
    }

    /**
     * Converts the UpdateSubscriptionSubscription object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateSubscriptionSubscription object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpdateSubscriptionSubscription',
            ['subscriptionNumber' => $this->subscriptionNumber, 'orderActions' => $this->orderActions]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        $json['subscriptionNumber'] = $this->subscriptionNumber;
        if (isset($this->orderActions)) {
            $json['orderActions']   = $this->orderActions;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
