<?php

declare(strict_types=1);

/*
 * PplusSubscriptionPapiLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PplusSubscriptionPapiLib\Models;

use PplusSubscriptionPapiLib\ApiHelper;
use stdClass;

class UpdateOrAddProductChargeOverride implements \JsonSerializable
{
    /**
     * @var string|null
     */
    private $productRatePlanChargeId;

    /**
     * @var CustomerFacingCustomFields|null
     */
    private $customerFacingCustomFields;

    /**
     * @var OverridesPricing|null
     */
    private $overridesPricing;

    /**
     * @var AddProductEndDate|null
     */
    private $addProductEndDate;

    /**
     * Returns Product Rate Plan Charge Id.
     * This is unique rate plan charge id respective to rate plan id. It signifies the subscription type,
     * entitlementLevel,maxEntitlements,numEntitlements etc.
     */
    public function getProductRatePlanChargeId(): ?string
    {
        return $this->productRatePlanChargeId;
    }

    /**
     * Sets Product Rate Plan Charge Id.
     * This is unique rate plan charge id respective to rate plan id. It signifies the subscription type,
     * entitlementLevel,maxEntitlements,numEntitlements etc.
     *
     * @maps productRatePlanChargeId
     */
    public function setProductRatePlanChargeId(?string $productRatePlanChargeId): void
    {
        $this->productRatePlanChargeId = $productRatePlanChargeId;
    }

    /**
     * Returns Customer Facing Custom Fields.
     */
    public function getCustomerFacingCustomFields(): ?CustomerFacingCustomFields
    {
        return $this->customerFacingCustomFields;
    }

    /**
     * Sets Customer Facing Custom Fields.
     *
     * @maps customerFacingCustomFields
     */
    public function setCustomerFacingCustomFields(?CustomerFacingCustomFields $customerFacingCustomFields): void
    {
        $this->customerFacingCustomFields = $customerFacingCustomFields;
    }

    /**
     * Returns Overrides Pricing.
     */
    public function getOverridesPricing(): ?OverridesPricing
    {
        return $this->overridesPricing;
    }

    /**
     * Sets Overrides Pricing.
     *
     * @maps overridesPricing
     */
    public function setOverridesPricing(?OverridesPricing $overridesPricing): void
    {
        $this->overridesPricing = $overridesPricing;
    }

    /**
     * Returns Add Product End Date.
     */
    public function getAddProductEndDate(): ?AddProductEndDate
    {
        return $this->addProductEndDate;
    }

    /**
     * Sets Add Product End Date.
     *
     * @maps addProductEndDate
     */
    public function setAddProductEndDate(?AddProductEndDate $addProductEndDate): void
    {
        $this->addProductEndDate = $addProductEndDate;
    }

    /**
     * Converts the UpdateOrAddProductChargeOverride object to a human-readable string representation.
     *
     * @return string The string representation of the UpdateOrAddProductChargeOverride object.
     */
    public function __toString(): string
    {
        return ApiHelper::stringify(
            'UpdateOrAddProductChargeOverride',
            [
                'productRatePlanChargeId' => $this->productRatePlanChargeId,
                'customerFacingCustomFields' => $this->customerFacingCustomFields,
                'overridesPricing' => $this->overridesPricing,
                'addProductEndDate' => $this->addProductEndDate
            ]
        );
    }

    /**
     * Encode this object to JSON
     *
     * @param bool $asArrayWhenEmpty Whether to serialize this model as an array whenever no fields
     *        are set. (default: false)
     *
     * @return array|stdClass
     */
    #[\ReturnTypeWillChange] // @phan-suppress-current-line PhanUndeclaredClassAttribute for (php < 8.1)
    public function jsonSerialize(bool $asArrayWhenEmpty = false)
    {
        $json = [];
        if (isset($this->productRatePlanChargeId)) {
            $json['productRatePlanChargeId']    = $this->productRatePlanChargeId;
        }
        if (isset($this->customerFacingCustomFields)) {
            $json['customerFacingCustomFields'] = $this->customerFacingCustomFields;
        }
        if (isset($this->overridesPricing)) {
            $json['overridesPricing']           = $this->overridesPricing;
        }
        if (isset($this->addProductEndDate)) {
            $json['addProductEndDate']          = $this->addProductEndDate;
        }

        return (!$asArrayWhenEmpty && empty($json)) ? new stdClass() : $json;
    }
}
