<?php

declare(strict_types=1);

/*
 * PearsonSubscriptionsAPILib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

namespace PearsonSubscriptionsAPILib\Models;

use Core\Utils\CoreHelper;
use Exception;
use stdClass;

/**
 * Unit of time that the charge duration is measured in. Only applicable if the value of the
 * endDateCondition field is Fixed_Period.
 */
class UpToPeriodsTypeEnum
{
    public const BILLING_PERIODS = 'Billing_Periods';

    public const DAYS = 'Days';

    public const WEEKS = 'Weeks';

    public const MONTHS = 'Months';

    public const YEARS = 'Years';

    private const _ALL_VALUES = [self::BILLING_PERIODS, self::DAYS, self::WEEKS, self::MONTHS, self::YEARS];

    /**
     * Ensures that all the given values are present in this Enum.
     *
     * @param array|stdClass|null|string $value Value or a list/map of values to be checked
     *
     * @return array|null|string Input value(s), if all are a part of this Enum
     *
     * @throws Exception Throws exception if any given value is not in this Enum
     */
    public static function checkValue($value)
    {
        $value = json_decode(json_encode($value), true); // converts stdClass into array
        if (CoreHelper::checkValueOrValuesInList($value, self::_ALL_VALUES)) {
            return $value;
        }
        throw new Exception("$value is invalid for UpToPeriodsTypeEnum.");
    }
}
